### ISSUE TITLE
how to add a configuration?

### ISSUE THREAD

**Issue by jots** [pavkum/vscode-hydra#1]
new to vscode.

how can we add for example the file operations configuration to hydra?
how do we create new configurations?

**Comment by pavkum** [comment]
@jots In order to configure, you have to edit the settings json. Please follow the steps below
1. Open command pallete
2. search for *open settings (JSON)* and click on it
3. Once you are in the settings file, create a new entry *hydra.commands* - it's a json array of objects

You can then use sample json from the examples for playing around.

Please let me know if you need any other information.

**Comment by jots** [comment]
thanks.  I added this block to my settings.json:
```
  "hydra.commands": [
        {
            "key": "f",
            "desc": "File operations commands",
            "children": [
                {
                    "key": "s",
[etc]
```
(from your file.json example).  however when I hit ctrl-p and type f  nothing pops up, no hints etc...

**Comment by pavkum** [comment]
@jots From 0.9.3 default shortcut has been changed to *alt+p*. My guess is *ctrl-p* might be invoking some different command according to your configuration.
Alternately, you search for "hydra" from command palette and key-in first input, in your case *f*

**Comment by jots** [comment]
I'm sorry, I meant alt-p.  it brings up the hydra input field at top, but typing in it doesn't show any hints.  however, if I do: "fn" "enter" it does open a new file.  but fNn doesn't work.  I'll mess around with it more later today.  I really like this concept!

**Comment by jots** [comment]
I should also mention that I'm using code-server (https://github.com/cdr/code-server) so perhaps it's a problem with that.

**Comment by pavkum** [comment]
Hmm, when I checked *code-server*, it's mentioned that they have some issues with extensions. Although, I'm not sure if the extension itself has any issues or due to code-server. 
Please let me know how it goes.

**Comment by jots** [comment]
On the debug panel I see:
`"$ref '/definitions/hydra' in 'vscode://schemas/settings/user' can not be resolved."`
may be a code-server issue.  I have no idea what a $ref is.

**Comment by pavkum** [comment]
That's a known issue. It can be safely ignored. It's the JSON schema of the configuration.

**Comment by pavkum** [comment]
*fNn* is binded to fileutils extension. I have mentioned that in comments of sample config. You need to install file-utils extension for it to work.

**Comment by pavkum** [comment]
closing due to inactiivity
